# Generated by Django 5.2.7 on 2025-11-02 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='notification_sent',
            field=models.BooleanField(default=False),
        ),
    ]
